version: '3.8'

services:
  steam-ban-watcher:
    build: .
    stop_signal: SIGINT
    depends_on:
      - database
    ports:
      - 8000:8000
    environment:
      DATABASE_URI: postgresql://steam-ban-watcher:wedontlikecheaterssowewatchthem@database/watcher
      STEAM_API_KEY: 
    restart: unless-stopped

  database:
    image: postgres:16.0-alpine
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: watcher
      POSTGRES_USER: steam-ban-watcher
      POSTGRES_PASSWORD: wedontlikecheaterssowewatchthem
    restart: unless-stopped
    
  proxy:
    build: proxy
    restart: unless-stopped
    ports:
    - 86:80
    depends_on:
      - steam-ban-watcher
    