version: '3.8'

services:
  steam-ban-watcher:
    image: ghcr.io/illumfx/steam-ban-watcher:master
    stop_signal: SIGINT
    depends_on:
      - database
    environment:
      DATABASE_URI: postgresql://steam-ban-watcher:wedontlikecheaterssowewatchthem@database/watcher
      TIMEZONE: Europe/Berlin
      STEAM_API_KEY: 
    restart: unless-stopped

  database:
    image: postgres:16.0-alpine
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: watcher
      POSTGRES_USER: steam-ban-watcher
      POSTGRES_PASSWORD: wedontlikecheaterssowewatchthem
    restart: unless-stopped
    
  proxy:
    image: nginx:1.13-alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    ports:
      - 86:80
    depends_on:
      - steam-ban-watcher
    